/**************************************************************************** 
 * Job:             MVBS_CASO_TDB                         A5V8BXSQ.AR0001I7 * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: bire-sas94-meta-dev.srv.allianz                         * 
 * Port:            8561                                                    * 
 * Location:        /ETL/tdbpcd/Jobs/MVBS/MVBS_OUTPUT                       * 
 *                                                                          * 
 * Server:          tdbpcd                                A5HYR2NS.AS00001O * 
 *                                                                          * 
 * Source Tables:   META_MVBS_AMOUNT_TYPE -               A5V8BXSQ.AE0001TX * 
 *                   RESASDWH.META_MVBS_AMOUNT_TYPE                         * 
 *                  MVBS_OUTPUT_4TECHDB2 -                A5V8BXSQ.AE0001WD * 
 *                   RESASDWH.MVBS_OUTPUT_4TECHDB2                          * 
 *                                                                          * 
 * Generated on:    Monday, August 28, 2017 3:12:52 PM IST                  * 
 * Generated by:    re00580                                                 * 
 * Version:         SAS Data Integration Studio 4.902                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5V8BXSQ.AR0001I7);
%let etls_jobName = %nrquote(MVBS_CASO_TDB);
%let etls_userID = %nrquote(re00580);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

/*Call to an initialization macro  */
%mvbsJobInit;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            Create Table                          A5V8BXSQ.AW0003YK * 
 * Transform:       Create Table                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    MVBS_OUTPUT_4TECHDB2 -                A5V8BXSQ.AE0001WD * 
 *                   RESASDWH.MVBS_OUTPUT_4TECHDB2                          * 
 * Target Table:    Create Table - work.TDB_output        A5V8BXSQ.AQ0001NM * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003YK);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(RESASDWH.MVBS_OUTPUT_4TECHDB2); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete TDB_output;
quit;

proc sql
;
create table work.TDB_output as
select
   MVBS_OUTPUT_4TECHDB2.LEGAL_ENTITY_CODE length = 6   
      format = $6.
      informat = $6.
      label = 'LEGAL_ENTITY_CODE',
   MVBS_OUTPUT_4TECHDB2.GROSSRETRO length = 44   
      format = $44.
      informat = $44.
      label = 'GROSSRETRO',
   MVBS_OUTPUT_4TECHDB2.AMT_TYPE length = 100   
      format = $100.
      informat = $100.
      label = 'AMT_TYPE',
   sum(MVBS_OUTPUT_4TECHDB2.EUR_AMOUNT) as EUR_AMOUNT length = 8   
      label = 'EUR_AMOUNT'
from
   RESASDWH.MVBS_OUTPUT_4TECHDB2 as MVBS_OUTPUT_4TECHDB2
where
   strip(upcase(MVBS_OUTPUT_4TECHDB2.DISCUNDISC)) = 'DISCOUNTED'
   and strip(upcase(MVBS_OUTPUT_4TECHDB2.PERIOD)) = 'TOTAL'
group by
   MVBS_OUTPUT_4TECHDB2.LEGAL_ENTITY_CODE,
   MVBS_OUTPUT_4TECHDB2.GROSSRETRO,
   MVBS_OUTPUT_4TECHDB2.AMT_TYPE
;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Create Table **/

/*==========================================================================* 
 * Step:            Create Table                          A5V8BXSQ.AW0003YL * 
 * Transform:       Create Table                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    META_MVBS_AMOUNT_TYPE -               A5V8BXSQ.AE0001TX * 
 *                   RESASDWH.META_MVBS_AMOUNT_TYPE                         * 
 * Target Table:    Create Table - work.amount_types      A5V8BXSQ.AQ0001NN * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003YL);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(RESASDWH.META_MVBS_AMOUNT_TYPE); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete amount_types;
quit;

proc sql
;
create table work.amount_types as
select
   META_MVBS_AMOUNT_TYPE.AMT_TYPE length = 20,
   META_MVBS_AMOUNT_TYPE.RM_TYPE length = 20,
   META_MVBS_AMOUNT_TYPE.RM_GROSSRETRO length = 5
from
   RESASDWH.META_MVBS_AMOUNT_TYPE as META_MVBS_AMOUNT_TYPE
where
   META_MVBS_AMOUNT_TYPE.RM_TYPE IS NOT NULL 
;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Create Table **/

/*==========================================================================* 
 * Step:            Create Table                          A5V8BXSQ.AW0003YM * 
 * Transform:       Create Table                                            * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Tables:   Create Table - work.TDB_output        A5V8BXSQ.AQ0001NM * 
 *                  Create Table - work.amount_types      A5V8BXSQ.AQ0001NN * 
 * Target Table:    Create Table - work.RM_sums           A5V8BXSQ.AQ0001NO * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003YM);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

proc datasets lib = work nolist nowarn memtype = (data view);
   delete RM_sums;
quit;

proc sql
;
create table work.RM_sums as
select
   TDB_output.LEGAL_ENTITY_CODE length = 6   
      format = $6.
      informat = $6.
      label = 'LEGAL_ENTITY_CODE',
   sum( 
      case 
         when amount_types.RM_TYPE is null then TDB_output.EUR_AMOUNT 
         else . 
      end 
   ) as RM length = 8   
      label = 'RM',
   sum( 
      case 
         when amount_types.RM_TYPE is not null then TDB_output.EUR_AMOUNT 
         else . 
      end 
   ) as TOTAL length = 8   
      label = 'TOTAL',
   'EUR' as CURRENCY length = 3   
      label = 'CURRENCY',
   round(calculated RM / calculated TOTAL * 100, .1) as PCT length = 8   
      label = 'PCT'
from
   work.TDB_output as TDB_output left join 
   work.amount_types as amount_types
      on
      (
         TDB_output.AMT_TYPE = amount_types.AMT_TYPE
         and TDB_output.GROSSRETRO = amount_types.RM_GROSSRETRO
      )
where
   amount_types.AMT_TYPE IS NOT NULL 
   or TDB_output.AMT_TYPE IN ('RM', 'ANNUITIES_RM')
group by
   TDB_output.LEGAL_ENTITY_CODE
;
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end Create Table **/

/*==========================================================================* 
 * Step:            MVBS TDB BULK_CSV_WRITE               A5V8BXSQ.AW0003YO * 
 * Transform:       MVBS TDB BULK_CSV_WRITE                                 * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    Create Table - work.RM_sums           A5V8BXSQ.AQ0001NO * 
 * Target Table:    MVBS BULK_CSV_WRITE_OUTPUT -          A5V8BXSQ.AQ0001NQ * 
 *                   work.csv_filenames                                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003YO);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.RM_sums); 

%let _INPUT_count = 1; 
%let _INPUT = work.RM_sums;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/Create Table_A5V8BXSQ.AQ0001NO%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.RM_sums;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/Create Table_A5V8BXSQ.AQ0001NO%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 1; 
%let _OUTPUT = work.csv_filenames;
%let _OUTPUT_connect = ;
%let _OUTPUT_engine = ;
%let _OUTPUT_memtype = DATA;
%let _OUTPUT_options = %nrquote();
%let _OUTPUT_alter = %nrquote();
%let _OUTPUT_path = %nrquote(/MVBS BULK_CSV_WRITE_OUTPUT_A5V8BXSQ.AQ0001NQ%(WorkTable%));
%let _OUTPUT_type = 1;
%let _OUTPUT_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_keep = Filename;

%let _OUTPUT_BULK_CSV = work.csv_filenames;
%let _OUTPUT_BULK_CSV_connect = ;
%let _OUTPUT_BULK_CSV_engine = ;
%let _OUTPUT_BULK_CSV_memtype = DATA;
%let _OUTPUT_BULK_CSV_options = %nrquote();
%let _OUTPUT_BULK_CSV_alter = %nrquote();
%let _OUTPUT_BULK_CSV_path = %nrquote(/MVBS BULK_CSV_WRITE_OUTPUT_A5V8BXSQ.AQ0001NQ%(WorkTable%));
%let _OUTPUT_BULK_CSV_type = 1;
%let _OUTPUT_BULK_CSV_label = %nrquote();
/* List of target columns to keep  */ 
%let _OUTPUT_BULK_CSV_keep = Filename;


%let filename = %nrquote(%str("mvbs_output/&sub._CASO_&reporting_period..csv"));
%let header_count = %nrquote(0);
%let header = ;
%let column = LEGAL_ENTITY_CODE CURRENCY RM TOTAL PCT;
%let column_count = 5;
%let column0 = 5;
%let column1 = LEGAL_ENTITY_CODE;
%let column2 = CURRENCY;
%let column3 = RM;
%let column4 = TOTAL;
%let column5 = PCT;
%let columnHeaders = %nrquote(YES);
%let file_open_mode = %nrquote(o);
%let by_group = ;
%let by_group_count = 0;
%let by_group0 = 0;
%let by_group = ;
%let orderbycolumn = ;
%let orderbycolumn_count = 0;
%let orderbycolumn0 = 0;
%let orderbycolumn = ;
%let path = ;
%let dlm = %nrquote(semi);
%let dlm1 = ;
%let where = ;
%let TERMSTR = %nrquote(TERMSTR=CRLF);

/* List of target columns to keep  */ 
%let _keep = Filename;
/* List of target columns to keep  */ 
%let keep = Filename;
/*****************************************************************************************************************************/
/*********** CODE FOR WRITING THE SELECTED INPUT COLUMNS TO EXTERANAL CSV FILE ***********************************************/
/*****************************************************************************************************************************/

options noquotelenmax;

/* New prompt file_open_mode introduced. Must have "o" as default value for compatibility reasons */
%global file_open_mode;
%let file_open_mode=%sysfunc(coalescec(&file_open_mode., o));

%macro define_delimiter;
%global dlm2;
%if  &dlm eq semi %then %do;
%let dlm2=%str(;);
%end;
%if  &dlm eq others %then %do;
data _null_;
call symput('dlm2',"&dlm1");
run;%end;
%if &dlm eq comma %then %do;
%let dlm2=%str(,);
%end;
%mend define_delimiter;
%define_delimiter;

data _null_;
length g $100.;
g=tranwrd("&orderbycolumn"," ",",");
call symput('orderbycol',compress(g));
run;

data _null_; 
length COlUMN_LIST $2000;  
if symget('column_count')=1 then COlUMN_LIST=trim(symget('column')); 
else do i=1 to symget('column_count'); 
COlUMN_LIST= catx("&dlm2" ,COlUMN_LIST, trim(symget(cats('column',i)))); 
end; 
if missing(COlUMN_LIST)=0 then 
call symputx('column_list',COlUMN_LIST); 
run; 

%macro dd3;
%if &orderbycolumn ne  %then %do;
proc sql;
create table order_table as select * from &_input
order by &orderbycol;
quit;
%end;
%mend dd3;
%dd3;

%macro produce_csv;
	%local firstDataRowOfGroup lastDataRowOfGroup byStatement;
	%if "&by_group." ne "" %then %do;
        %let byStatement = %str(by &by_group;);
		%let firstDataRowOfGroup = first.%scan(&by_group., %sysfunc(countw(&by_group.)));
		%let lastDataRowOfGroup  = last.%scan(&by_group., %sysfunc(countw(&by_group.)));
	%end;
	%else %do;
        %let byStatement = ;
		%let firstDataRowOfGroup = %str(_N_=1);
		%let lastDataRowOfGroup  = %str(eof=1);
	%end;

	/* check whether an output table is defined to collect all filenames of CSV files that are created in this step */
	%local outTable outKeep;

	%if %symexist(_OUTPUT_BULK_CSV) = 1 %then %do;
		%if %quote(&_OUTPUT_BULK_CSV.) eq %then %do;
			/* No output table defined, set output to _null_ for the following data step */
			%let outTable = _null_;
			%let outKeep = ;
		%end;
		%else %do;
			/* Output table defined, set local variables outTable and outKeep */
			%let outTable = &_OUTPUT_BULK_CSV.;
			%let outKeep = (keep=&_OUTPUT_BULK_CSV_keep.);
		%end;
	%end;
	%else %do;
			/*
			 * No output table defined, set output to _null_ for the following data step.
			 * Create a local dummy macro variable in order to avoid warnings/errors when executing the rest of the code
			 * (which relies on an existing macro variable).
			 */
		%local _OUTPUT_BULK_CSV;
		%let outTable = _null_;
		%let outKeep = ;
	%end;

	data &outTable.&outKeep.;
		%if "&orderbycolumn" ne "" %then %do;
			set order_table end=eof;
		%end;
		%else %do;
			set &_input end=eof;
		%end;
		where &where.;
		length column_put $2000 filename $1000 header $2000;
		retain file_count 0 file_id;

		&byStatement.

		if &firstDataRowOfGroup. then do;
			filename = strip("&proj_env./data/" || &filename.);
			rc = filename('ft' || strip(file_count), strip(filename) , 'DISK' , "&TERMSTR.");			
			file_id = fopen('ft' || strip(file_count), "&file_open_mode.", 1000, 'v');
			%do header_nr = 1 %to &header_count.;
				%let my_header = %sysfunc(trim(&&header&header_nr.));
				header = trim(&my_header.);
				rcp = fput(file_id, strip(header));
				rcw = fwrite(file_id);
			%end;
			%if %upcase(&columnHeaders.) eq YES %then %do;
				rcp = fput(file_id, "&column_list.");
				rcw = fwrite(file_id);
			%end;
			%else %if %upcase(&columnHeaders.) eq LABELS %then %do;
				header = strip(vlabelx(scan("&column.", 1)));
				do count = 2 to countw("&column.");
					col = scan("&column.", count);
					header = strip(header) || "&dlm2" || strip(vlabelx(col));
				end;
				rcp = fput(file_id, strip(header));
				rcw = fwrite(file_id);
			%end;

			%if %quote(&_OUTPUT_BULK_CSV.) ne %then %do;
				/* Add current file name to the output table containing all file names. */
				output &outTable.;
			%end;

			file_count + 1;
		end;
 
/*      if  ( ifc(index(upcase("&column"),"NOMINAL")>1, vvaluex(scan("&column.", 5)),1) ne  0 ) */
/*         then do;*/

		/* If condition - added as part of user story TDB-156. */
			column_put = strip(vvaluex(scan("&column.", 1)));
			do count = 2 to countw("&column.");
				col = scan("&column.", count);
				column_put = strip(column_put) || "&dlm2" || strip(vvaluex(col));
			end;
			rcp = fput(file_id, strip(column_put));
			rcw = fwrite(file_id);
/*     end;*/
		if &lastDataRowOfGroup. then do;
			rcc = fclose(file_id);

			%if %quote(&_OUTPUT_BULK_CSV.) eq %then %do;
				/* No output table defined -> add files directly to a zip file (default beaviour until 2015Q3 release) */
				%if "&path" eq "" %then %do;
					call execute('ods package(LongRun) add file=' ||'"' || strip("&proj_env/data/" || &filename.)  || '"' ||';');
				%end;
				%else %do;
					call execute('ods package(LongRun) add file=' ||'"' || strip("&proj_env/data/" || &filename.)  || '"' 
									|| ' path =' || '"' || &path. || '"' ||';');
				%end;
			%end;
		end;
	run;

	/* Delete output macro variable, just to be sure that no subsequent "BULK CSV write" gets in trouble */
	%symdel _OUTPUT_BULK_CSV;
%mend;
%produce_csv;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end MVBS TDB BULK_CSV_WRITE **/

/*==========================================================================* 
 * Step:            MVBS TDB Create zip file              A5V8BXSQ.AW0003YP * 
 * Transform:       MVBS TDB Create zip file                                * 
 * Description:                                                             * 
 *                                                                          * 
 * Source Table:    MVBS BULK_CSV_WRITE_OUTPUT -          A5V8BXSQ.AQ0001NQ * 
 *                   work.csv_filenames                                     * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003YP);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(work.csv_filenames); 

%let _INPUT_count = 1; 
%let _INPUT = work.csv_filenames;
%let _INPUT_connect = ;
%let _INPUT_engine = ;
%let _INPUT_memtype = DATA;
%let _INPUT_options = %nrquote();
%let _INPUT_alter = %nrquote();
%let _INPUT_path = %nrquote(/MVBS BULK_CSV_WRITE_OUTPUT_A5V8BXSQ.AQ0001NQ%(WorkTable%));
%let _INPUT_type = 1;
%let _INPUT_label = %nrquote();

%let _INPUT0 = work.csv_filenames;
%let _INPUT0_connect = ;
%let _INPUT0_engine = ;
%let _INPUT0_memtype = DATA;
%let _INPUT0_options = %nrquote();
%let _INPUT0_alter = %nrquote();
%let _INPUT0_path = %nrquote(/MVBS BULK_CSV_WRITE_OUTPUT_A5V8BXSQ.AQ0001NQ%(WorkTable%));
%let _INPUT0_type = 1;
%let _INPUT0_label = %nrquote();

%let _OUTPUT_count = 0; 

%let zipFilePath = %nrquote(&proj_env./data/mvbs_output/);
%let zipFileName = %nrquote(%str("&sub._CASO.zip"));

%macro createZIP;
   /* Open a new zip archive */
   ods package open nopf;

   /* Add the required files to the zip archive */	
	%do inputCount=0 %to %eval(&_INPUT_count. - 1);
	   data _null_;
	      length filename path $1000;
	      set &&_INPUT&inputCount;
	
	      if missing(path) then
	         call execute('ods package add file="' || strip(filename) || '";');
	      else
	         call execute('ods package add file="' || strip(filename) || '"  path = "' || strip(path) || '";');
	   run;
	%end;
	
   /*
    * Store the zip archive to the file system.
    * No quotation marks around zipFileName because this macro variable may contain ANY statement
    * (and therefore must also take care of the quotes).
    */
   ods package publish archive properties(archive_name=&zipFileName. archive_path="&zipFilePath.");

   /* Close the zip archive and delete the ods package object */
   ods package close;
%mend;

%createZIP;

%rcSet(&syserr); 
%rcSet(&sysrc); 
%rcSet(&sqlrc); 



/**  Step end MVBS TDB Create zip file **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/* Check return code for job  */ 
%macro etls_jobRCChk; 
   %if (&job_rc ge 5) %then
   %do; 
      %macro etls_sendEmail(address=, message=); 
      
         filename sendMail email "&address" subject='ETL Process Status'; 
      
         %local etls_syntaxcheck; 
         %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
         /* Turn off syntaxcheck option to perform following steps  */ 
         options nosyntaxcheck;
      
         data _null_; 
            file sendMail; 
            dttm = put(datetime(),nldatm.); 
            put dttm "&message."; 
         run; 
      
         /* Reset syntaxcheck option to previous setting  */ 
         options &etls_syntaxcheck; 
      %mend etls_sendEmail; 
      %etls_sendEmail 
         (address = &mail_to, 
          Message = %str(&etls_jobName Error auf &run_system : Error%%superq%(syserrortext%))); 
   %end; 
%mend etls_jobRCChk; 
%etls_jobRCChk; 

/* Check return code for job  */ 
%macro etls_jobRCChk; 
   %if (&job_rc ge 5) %then
   %do; 
      %macro etls_sendFile(directory=, filename=, message=); 
      
         filename sendfile "&directory.&filename"; 
      
         %local etls_syntaxcheck; 
         %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
         /* Turn off syntaxcheck option to perform following steps  */ 
         options nosyntaxcheck;
      
         data _null_; 
            file sendFile; 
            dttm = put(datetime(),nldatm.); 
            put dttm "&message."; 
         run; 
      
         /* Reset syntaxcheck option to previous setting  */ 
         options &etls_syntaxcheck; 
      %mend etls_sendFile; 
      %etls_sendFile 
         (FileName = &proj_env./run_control/mvbs_error_&etls_jobName, 
          Message = Error); 
   %end; 
%mend etls_jobRCChk; 
%etls_jobRCChk; 

