/**************************************************************************** 
 * Job:             MVBS_CASO_REPORT2                     A5V8BXSQ.AR0001BV * 
 * Description:                                                             * 
 *                                                                          * 
 * Metadata Server: bire-sas94-meta-dev.srv.allianz                         * 
 * Port:            8561                                                    * 
 * Location:        /ETL/tdbpcd/Jobs/MVBS/MVBS_REPORTING                    * 
 *                                                                          * 
 * Server:          tdbpcd                                A5HYR2NS.AS00001O * 
 *                                                                          * 
 * Source Tables:   MVBS_OUTPUT - RESASDWH.MVBS_OUTPUT    A5V8BXSQ.AE0001W7 * 
 *                  MVBS_LOG - RESASDWH.MVBS_LOG          A5V8BXSQ.AE0001W3 * 
 *                  MVBS_CASO_REPORT2_ABS -               A5V8BXSQ.AE0001UZ * 
 *                   RESASDWH.MVBS_CASO_REPORT2_ABS                         * 
 * Target Tables:   MVBS_CASO_REPORT2_ABS -               A5V8BXSQ.AE0001UZ * 
 *                   RESASDWH.MVBS_CASO_REPORT2_ABS                         * 
 *                  MVBS_CASO_REPORT2_REL -               A5V8BXSQ.AE0001V0 * 
 *                   RESASDWH.MVBS_CASO_REPORT2_REL                         * 
 *                                                                          * 
 * Generated on:    Tuesday, January 24, 2017 3:55:27 PM IST                * 
 * Generated by:    re00580                                                 * 
 * Version:         SAS Data Integration Studio 4.901                       * 
 ****************************************************************************/ 

/* Generate the process id for job  */ 
%put Process ID: &SYSJOBID;

/* General macro variables  */ 
%let jobID = %quote(A5V8BXSQ.AR0001BV);
%let etls_jobName = %nrquote(MVBS_CASO_REPORT2);
%let etls_userID = %nrquote(re00580);

/* Setup to capture return codes  */ 
%global job_rc trans_rc sqlrc;
%let sysrc = 0;
%let job_rc = 0;
%let trans_rc = 0;
%let sqlrc = 0;
%global etls_stepStartTime; 
/* initialize syserr to 0 */
data _null_; run;

%macro rcSet(error); 
   %if (&error gt &trans_rc) %then 
      %let trans_rc = &error;
   %if (&error gt &job_rc) %then 
      %let job_rc = &error;
%mend rcSet; 

%macro rcSetDS(error); 
   if &error gt input(symget('trans_rc'),12.) then 
      call symput('trans_rc',trim(left(put(&error,12.))));
   if &error gt input(symget('job_rc'),12.) then 
      call symput('job_rc',trim(left(put(&error,12.))));
%mend rcSetDS; 

/* Create metadata macro variables */
%let IOMServer      = %nrquote(tdbpcd);
%let metaPort       = %nrquote(8561);
%let metaServer     = %nrquote(ibire-sas94-meta-dev.srv.allianz);

/* Setup for capturing job status  */ 
%let etls_startTime = %sysfunc(datetime(),datetime.);
%let etls_recordsBefore = 0;
%let etls_recordsAfter = 0;
%let etls_lib = 0;
%let etls_table = 0;

%global etls_debug; 
%macro etls_setDebug; 
   %if %str(&etls_debug) ne 0 %then 
      OPTIONS MPRINT%str(;); 
%mend; 
%etls_setDebug; 

/*---- Start of Pre-Process Code  ----*/ 

/*Call to an initialization macro  */
%mvbsJobInit;
/*---- End of Pre-Process Code  ----*/ 

%rcSet(&syserr); 
%rcSet(&sqlrc); 

/*==========================================================================* 
 * Step:            SQL Join                              A5V8BXSQ.AW0003H4 * 
 * Transform:       Join                                                    * 
 * Description:     Calculation of AMOUNTS based on PERIOD values           * 
 *                                                                          * 
 * Source Tables:   MVBS_OUTPUT - RESASDWH.MVBS_OUTPUT    A5V8BXSQ.AE0001W7 * 
 *                  MVBS_LOG - RESASDWH.MVBS_LOG          A5V8BXSQ.AE0001W3 * 
 * Target Table:    MVBS_CASO_REPORT2_ABS -               A5V8BXSQ.AE0001UZ * 
 *                   RESASDWH.MVBS_CASO_REPORT2_ABS                         * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003H4);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%macro etls_prepareTarget();
   proc datasets lib = RESASDWH nolist nowarn memtype = (data view);
      delete MVBS_CASO_REPORT2_ABS;
   quit;
   
   /*---- Create a new table  ----*/ 
   data RESASDWH.MVBS_CASO_REPORT2_ABS
           (dbnull = (
                      DISCUNDISC = YES
                      LEGAL_ENTITY_CODE = YES
                      GROSSRETRO = YES
                      AMT_TYPE = YES
                      AMOUNT_TOTAL = YES
                      AMOUNT_1 = YES
                      AMOUNT_2 = YES
                      AMOUNT_3 = YES
                      AMOUNT_4 = YES
                      AMOUNT_5 = YES
                      AMOUNT_6 = YES
                      AMOUNT_7 = YES
                      AMOUNT_8 = YES
                      AMOUNT_9 = YES
                      AMOUNT_10 = YES
                      AMOUNT_11 = YES
                      AMOUNT_12 = YES
                      AMOUNT_13 = YES
                      AMOUNT_14 = YES
                      AMOUNT_15 = YES
                      AMOUNT_16 = YES
                      AMOUNT_17 = YES
                      AMOUNT_18 = YES
                      AMOUNT_19 = YES
                      AMOUNT_20 = YES
                      AMOUNT_21 = YES
                      AMOUNT_22 = YES
                      AMOUNT_23 = YES
                      AMOUNT_24 = YES
                      AMOUNT_25 = YES
                      AMOUNT_26 = YES
                      AMOUNT_27 = YES
                      AMOUNT_28 = YES
                      AMOUNT_29 = YES
                      AMOUNT_30 = YES
                      AMOUNT_31 = YES
                      AMOUNT_32 = YES
                      AMOUNT_33 = YES
                      AMOUNT_34 = YES
                      AMOUNT_35 = YES
                      AMOUNT_36 = YES
                      AMOUNT_37 = YES
                      AMOUNT_38 = YES
                      AMOUNT_39 = YES
                      AMOUNT_40 = YES
                      AMOUNT_41 = YES
                      AMOUNT_42 = YES
                      AMOUNT_43 = YES
                      AMOUNT_44 = YES
                      AMOUNT_45 = YES
                      AMOUNT_46 = YES
                      AMOUNT_47 = YES
                      AMOUNT_48 = YES
                      AMOUNT_49 = YES));
      attrib DISCUNDISC length = $100
         format = $100.
         informat = $100.
         label = 'DISCUNDISC'; 
      attrib LEGAL_ENTITY_CODE length = $6
         format = $6.
         informat = $6.
         label = 'LEGAL_ENTITY_CODE'; 
      attrib GROSSRETRO length = $10
         format = $10.
         informat = $10.
         label = 'GROSSRETRO'; 
      attrib AMT_TYPE length = $100
         format = $100.
         informat = $100.
         label = 'AMT_TYPE'; 
      attrib AMOUNT_TOTAL length = 8
         label = 'AMOUNT_TOTAL'; 
      attrib AMOUNT_1 length = 8
         label = 'AMOUNT_1'; 
      attrib AMOUNT_2 length = 8
         label = 'AMOUNT_2'; 
      attrib AMOUNT_3 length = 8
         label = 'AMOUNT_3'; 
      attrib AMOUNT_4 length = 8
         label = 'AMOUNT_4'; 
      attrib AMOUNT_5 length = 8
         label = 'AMOUNT_5'; 
      attrib AMOUNT_6 length = 8
         label = 'AMOUNT_6'; 
      attrib AMOUNT_7 length = 8
         label = 'AMOUNT_7'; 
      attrib AMOUNT_8 length = 8
         label = 'AMOUNT_8'; 
      attrib AMOUNT_9 length = 8
         label = 'AMOUNT_9'; 
      attrib AMOUNT_10 length = 8
         label = 'AMOUNT_10'; 
      attrib AMOUNT_11 length = 8
         label = 'AMOUNT_11'; 
      attrib AMOUNT_12 length = 8
         label = 'AMOUNT_12'; 
      attrib AMOUNT_13 length = 8
         label = 'AMOUNT_13'; 
      attrib AMOUNT_14 length = 8
         label = 'AMOUNT_14'; 
      attrib AMOUNT_15 length = 8
         label = 'AMOUNT_15'; 
      attrib AMOUNT_16 length = 8
         label = 'AMOUNT_16'; 
      attrib AMOUNT_17 length = 8
         label = 'AMOUNT_17'; 
      attrib AMOUNT_18 length = 8
         label = 'AMOUNT_18'; 
      attrib AMOUNT_19 length = 8
         label = 'AMOUNT_19'; 
      attrib AMOUNT_20 length = 8
         label = 'AMOUNT_20'; 
      attrib AMOUNT_21 length = 8
         label = 'AMOUNT_21'; 
      attrib AMOUNT_22 length = 8
         label = 'AMOUNT_22'; 
      attrib AMOUNT_23 length = 8
         label = 'AMOUNT_23'; 
      attrib AMOUNT_24 length = 8
         label = 'AMOUNT_24'; 
      attrib AMOUNT_25 length = 8
         label = 'AMOUNT_25'; 
      attrib AMOUNT_26 length = 8
         label = 'AMOUNT_26'; 
      attrib AMOUNT_27 length = 8
         label = 'AMOUNT_27'; 
      attrib AMOUNT_28 length = 8
         label = 'AMOUNT_28'; 
      attrib AMOUNT_29 length = 8
         label = 'AMOUNT_29'; 
      attrib AMOUNT_30 length = 8
         label = 'AMOUNT_30'; 
      attrib AMOUNT_31 length = 8
         label = 'AMOUNT_31'; 
      attrib AMOUNT_32 length = 8
         label = 'AMOUNT_32'; 
      attrib AMOUNT_33 length = 8
         label = 'AMOUNT_33'; 
      attrib AMOUNT_34 length = 8
         label = 'AMOUNT_34'; 
      attrib AMOUNT_35 length = 8
         label = 'AMOUNT_35'; 
      attrib AMOUNT_36 length = 8
         label = 'AMOUNT_36'; 
      attrib AMOUNT_37 length = 8
         label = 'AMOUNT_37'; 
      attrib AMOUNT_38 length = 8
         label = 'AMOUNT_38'; 
      attrib AMOUNT_39 length = 8
         label = 'AMOUNT_39'; 
      attrib AMOUNT_40 length = 8
         label = 'AMOUNT_40'; 
      attrib AMOUNT_41 length = 8
         label = 'AMOUNT_41'; 
      attrib AMOUNT_42 length = 8
         label = 'AMOUNT_42'; 
      attrib AMOUNT_43 length = 8
         label = 'AMOUNT_43'; 
      attrib AMOUNT_44 length = 8
         label = 'AMOUNT_44'; 
      attrib AMOUNT_45 length = 8
         label = 'AMOUNT_45'; 
      attrib AMOUNT_46 length = 8
         label = 'AMOUNT_46'; 
      attrib AMOUNT_47 length = 8
         label = 'AMOUNT_47'; 
      attrib AMOUNT_48 length = 8
         label = 'AMOUNT_48'; 
      attrib AMOUNT_49 length = 8
         label = 'AMOUNT_49'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%mend etls_prepareTarget;
%etls_prepareTarget;

proc sql;
   connect to ORACLE
   ( 
       DBMAX_TEXT=32767 PATH="&ORA_RESASDWH_PATH" user="&ORA_RESASDWH_USER" pw="&ORA_RESASDWH_PWD"
   ); 
   execute 
   ( 
      insert into &ORA_RESASDWH_SCHEMA..MVBS_CASO_REPORT2_ABS
      select
         mvbs_output.DISCUNDISC,
         mvbs_output.LEGAL_ENTITY_CODE,
         mvbs_output.GROSSRETRO,
         mvbs_output.AMT_TYPE,
         sum(case when upper(trim(mvbs_output.PERIOD )) != 'TOTAL'  
          THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_TOTAL,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '1'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_1,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '2'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_2,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '3'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_3,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '4'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_4,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '5'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_5,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '6'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_6,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '7'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_7,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '8'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_8,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '9'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_9,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '10'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_10,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '11'
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_11,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '12'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_12,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '13' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_13,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '14'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_14,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '15' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_15,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '16'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_16,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '17' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_17,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '18'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_18,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '19' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_19,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '20'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_20,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '21' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_21,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '22'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_22,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '23' 
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_23,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '24'     THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_24,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '25'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_25,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '26'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_26,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '27'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_27,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '28'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_28,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '29'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_29,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '30'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_30,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '31'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_31,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '32'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_32,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '33'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_33,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '34'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_34,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '35'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_35,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '36'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_36,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '37'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_37,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '38'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_38,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '39'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_39,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '40'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_40,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '41'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_41,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '42'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_42,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '43'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_43,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '44'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_44,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '45'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_45,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '46'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_46,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '47'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_47,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '48'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_48,
         sum(case when upper(trim(mvbs_output.PERIOD )) =  '49'  
            THEN mvbs_output.AMOUNT  ELSE 0 END ) as AMOUNT_49
      from
         (
            select
               MVBS_OUTPUT.LINE_NUMBER,
               MVBS_OUTPUT.FILENAME,
               MVBS_OUTPUT.DISCUNDISC,
               MVBS_OUTPUT.LEGAL_ENTITY_NAME,
               MVBS_OUTPUT.MANDANT_ID,
               MVBS_OUTPUT.PROP_NONPROP,
               MVBS_OUTPUT.CEDENT_DOM_ID,
               MVBS_OUTPUT.INTEXT,
               MVBS_OUTPUT.CONVENTIONAL_SCOB_IN_SICS,
               MVBS_OUTPUT.RES_SEG_LEVEL1,
               MVBS_OUTPUT.RES_SEG_LEVEL2,
               MVBS_OUTPUT.RES_SEG_LEVEL3,
               MVBS_OUTPUT.RES_SEG_LEVEL4,
               MVBS_OUTPUT.RES_SEG_LEVEL5,
               MVBS_OUTPUT.CURR_TO_USE,
               MVBS_OUTPUT.INWARD_BUS_ID,
               MVBS_OUTPUT.OUTWARD_BUS_ID,
               MVBS_OUTPUT.PARTNER_ID_RETRO,
               MVBS_OUTPUT.VBUND_RETRO,
               MVBS_OUTPUT.INTEXT_RETRO,
               MVBS_OUTPUT.REL_YR_ID,
               MVBS_OUTPUT.REL_YR_VAL,
               MVBS_OUTPUT.LRDB_VAL_DATE,
               MVBS_OUTPUT.AMT_TYPE,
               MVBS_OUTPUT.GROSSRETRO,
               MVBS_OUTPUT.PERIOD,
               MVBS_OUTPUT.EUR_AMOUNT,
               MVBS_OUTPUT.AMOUNT,
               MVBS_OUTPUT.PARTNER_ID_GROSS,
               MVBS_OUTPUT.VBUND_GROSS,
               MVBS_OUTPUT.SEGMENT,
               MVBS_OUTPUT.LEGAL_ENTITY_CODE,
               MVBS_OUTPUT.REGION,
               MVBS_OUTPUT.COUNTRY_ID_TECHDB,
               MVBS_OUTPUT.ABACUS_SII_LOB,
               MVBS_OUTPUT.CARVE_OUT_LOB,
               MVBS_OUTPUT.GUIDE_6_LOB,
               MVBS_OUTPUT.SUPER_LOB,
               MVBS_OUTPUT.SII_LOB_CODE,
               MVBS_OUTPUT.SII_LOB_STRING,
               MVBS_OUTPUT.SM_LOB,
               MVBS_OUTPUT.PARTNER_ID_GROSS_DERIVED,
               MVBS_OUTPUT.PROP_NONPROP_RETRO,
               MVBS_OUTPUT.LOAD_TIMESTAMP,
               MVBS_OUTPUT.VERSION_ID
            from
               &ORA_RESASDWH_SCHEMA..MVBS_OUTPUT MVBS_OUTPUT
            where
               MVBS_OUTPUT.VERSION_ID IN (
                  select distinct
                     MVBS_LOG.VERSION_ID
                  from
                     &ORA_RESASDWH_SCHEMA..MVBS_LOG MVBS_LOG
                  where
                     MVBS_LOG.BUSINESS_UNIT = 'PC'
                     and MVBS_LOG.REPORTING_PERIOD = %sysfunc(compress(%str(%')&reporting_period.%str(%')))
               )
         ) mvbs_output
      group by
         mvbs_output.DISCUNDISC,
         mvbs_output.LEGAL_ENTITY_CODE,
         mvbs_output.GROSSRETRO,
         mvbs_output.AMT_TYPE
      
   ) by ORACLE; 
   
   %rcSet(&sqlrc); 
   
   disconnect from ORACLE; 
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end SQL Join **/

/*==========================================================================* 
 * Step:            SQL Join                              A5V8BXSQ.AW0003H5 * 
 * Transform:       Join                                                    * 
 * Description:     Calculation of percentages OF amounts                   * 
 *                                                                          * 
 * Source Table:    MVBS_CASO_REPORT2_ABS -               A5V8BXSQ.AE0001UZ * 
 *                   RESASDWH.MVBS_CASO_REPORT2_ABS                         * 
 * Target Table:    MVBS_CASO_REPORT2_REL -               A5V8BXSQ.AE0001V0 * 
 *                   RESASDWH.MVBS_CASO_REPORT2_REL                         * 
 *==========================================================================*/ 

%let transformID = %quote(A5V8BXSQ.AW0003H5);
%let trans_rc = 0;
%let etls_stepStartTime = %sysfunc(datetime(), datetime20.); 

%let SYSLAST = %nrquote(RESASDWH.MVBS_CASO_REPORT2_ABS); 

%global etls_sql_pushDown;
%let etls_sql_pushDown = -1;
option DBIDIRECTEXEC;

%macro etls_prepareTarget();
   proc datasets lib = RESASDWH nolist nowarn memtype = (data view);
      delete MVBS_CASO_REPORT2_REL;
   quit;
   
   /*---- Create a new table  ----*/ 
   data RESASDWH.MVBS_CASO_REPORT2_REL
           (dbnull = (
                      DISCUNDISC = YES
                      LEGAL_ENTITY_CODE = YES
                      GROSSRETRO = YES
                      AMT_TYPE = YES
                      AMOUNT_PERCENTAGE_TOTAL = YES
                      AMOUNT_PERCENTAGE_1 = YES
                      AMOUNT_PERCENTAGE_2 = YES
                      AMOUNT_PERCENTAGE_3 = YES
                      AMOUNT_PERCENTAGE_4 = YES
                      AMOUNT_PERCENTAGE_5 = YES
                      AMOUNT_PERCENTAGE_6 = YES
                      AMOUNT_PERCENTAGE_7 = YES
                      AMOUNT_PERCENTAGE_8 = YES
                      AMOUNT_PERCENTAGE_9 = YES
                      AMOUNT_PERCENTAGE_10 = YES
                      AMOUNT_PERCENTAGE_11 = YES
                      AMOUNT_PERCENTAGE_12 = YES
                      AMOUNT_PERCENTAGE_13 = YES
                      AMOUNT_PERCENTAGE_14 = YES
                      AMOUNT_PERCENTAGE_15 = YES
                      AMOUNT_PERCENTAGE_16 = YES
                      AMOUNT_PERCENTAGE_17 = YES
                      AMOUNT_PERCENTAGE_18 = YES
                      AMOUNT_PERCENTAGE_19 = YES
                      AMOUNT_PERCENTAGE_20 = YES
                      AMOUNT_PERCENTAGE_21 = YES
                      AMOUNT_PERCENTAGE_22 = YES
                      AMOUNT_PERCENTAGE_23 = YES
                      AMOUNT_PERCENTAGE_24 = YES
                      AMOUNT_PERCENTAGE_25 = YES
                      AMOUNT_PERCENTAGE_26 = YES
                      AMOUNT_PERCENTAGE_27 = YES
                      AMOUNT_PERCENTAGE_28 = YES
                      AMOUNT_PERCENTAGE_29 = YES
                      AMOUNT_PERCENTAGE_30 = YES
                      AMOUNT_PERCENTAGE_31 = YES
                      AMOUNT_PERCENTAGE_32 = YES
                      AMOUNT_PERCENTAGE_33 = YES
                      AMOUNT_PERCENTAGE_34 = YES
                      AMOUNT_PERCENTAGE_35 = YES
                      AMOUNT_PERCENTAGE_36 = YES
                      AMOUNT_PERCENTAGE_37 = YES
                      AMOUNT_PERCENTAGE_38 = YES
                      AMOUNT_PERCENTAGE_39 = YES
                      AMOUNT_PERCENTAGE_40 = YES
                      AMOUNT_PERCENTAGE_41 = YES
                      AMOUNT_PERCENTAGE_42 = YES
                      AMOUNT_PERCENTAGE_43 = YES
                      AMOUNT_PERCENTAGE_44 = YES
                      AMOUNT_PERCENTAGE_45 = YES
                      AMOUNT_PERCENTAGE_46 = YES
                      AMOUNT_PERCENTAGE_47 = YES
                      AMOUNT_PERCENTAGE_48 = YES
                      AMOUNT_PERCENTAGE_49 = YES));
      attrib DISCUNDISC length = $100
         format = $100.
         informat = $100.
         label = 'DISCUNDISC'; 
      attrib LEGAL_ENTITY_CODE length = $6
         format = $6.
         informat = $6.
         label = 'LEGAL_ENTITY_CODE'; 
      attrib GROSSRETRO length = $10
         format = $10.
         informat = $10.
         label = 'GROSSRETRO'; 
      attrib AMT_TYPE length = $100
         format = $100.
         informat = $100.
         label = 'AMT_TYPE'; 
      attrib AMOUNT_PERCENTAGE_TOTAL length = 8
         label = 'AMOUNT_PERCENTAGE_TOTAL'; 
      attrib AMOUNT_PERCENTAGE_1 length = 8
         label = 'AMOUNT_PERCENTAGE_1'; 
      attrib AMOUNT_PERCENTAGE_2 length = 8
         label = 'AMOUNT_PERCENTAGE_2'; 
      attrib AMOUNT_PERCENTAGE_3 length = 8
         label = 'AMOUNT_PERCENTAGE_3'; 
      attrib AMOUNT_PERCENTAGE_4 length = 8
         label = 'AMOUNT_PERCENTAGE_4'; 
      attrib AMOUNT_PERCENTAGE_5 length = 8
         label = 'AMOUNT_PERCENTAGE_5'; 
      attrib AMOUNT_PERCENTAGE_6 length = 8
         label = 'AMOUNT_PERCENTAGE_6'; 
      attrib AMOUNT_PERCENTAGE_7 length = 8
         label = 'AMOUNT_PERCENTAGE_7'; 
      attrib AMOUNT_PERCENTAGE_8 length = 8
         label = 'AMOUNT_PERCENTAGE_8'; 
      attrib AMOUNT_PERCENTAGE_9 length = 8
         label = 'AMOUNT_PERCENTAGE_9'; 
      attrib AMOUNT_PERCENTAGE_10 length = 8
         label = 'AMOUNT_PERCENTAGE_10'; 
      attrib AMOUNT_PERCENTAGE_11 length = 8
         label = 'AMOUNT_PERCENTAGE_11'; 
      attrib AMOUNT_PERCENTAGE_12 length = 8
         label = 'AMOUNT_PERCENTAGE_12'; 
      attrib AMOUNT_PERCENTAGE_13 length = 8
         label = 'AMOUNT_PERCENTAGE_13'; 
      attrib AMOUNT_PERCENTAGE_14 length = 8
         label = 'AMOUNT_PERCENTAGE_14'; 
      attrib AMOUNT_PERCENTAGE_15 length = 8
         label = 'AMOUNT_PERCENTAGE_15'; 
      attrib AMOUNT_PERCENTAGE_16 length = 8
         label = 'AMOUNT_PERCENTAGE_16'; 
      attrib AMOUNT_PERCENTAGE_17 length = 8
         label = 'AMOUNT_PERCENTAGE_17'; 
      attrib AMOUNT_PERCENTAGE_18 length = 8
         label = 'AMOUNT_PERCENTAGE_18'; 
      attrib AMOUNT_PERCENTAGE_19 length = 8
         label = 'AMOUNT_PERCENTAGE_19'; 
      attrib AMOUNT_PERCENTAGE_20 length = 8
         label = 'AMOUNT_PERCENTAGE_20'; 
      attrib AMOUNT_PERCENTAGE_21 length = 8
         label = 'AMOUNT_PERCENTAGE_21'; 
      attrib AMOUNT_PERCENTAGE_22 length = 8
         label = 'AMOUNT_PERCENTAGE_22'; 
      attrib AMOUNT_PERCENTAGE_23 length = 8
         label = 'AMOUNT_PERCENTAGE_23'; 
      attrib AMOUNT_PERCENTAGE_24 length = 8
         label = 'AMOUNT_PERCENTAGE_24'; 
      attrib AMOUNT_PERCENTAGE_25 length = 8
         label = 'AMOUNT_PERCENTAGE_25'; 
      attrib AMOUNT_PERCENTAGE_26 length = 8
         label = 'AMOUNT_PERCENTAGE_26'; 
      attrib AMOUNT_PERCENTAGE_27 length = 8
         label = 'AMOUNT_PERCENTAGE_27'; 
      attrib AMOUNT_PERCENTAGE_28 length = 8
         label = 'AMOUNT_PERCENTAGE_28'; 
      attrib AMOUNT_PERCENTAGE_29 length = 8
         label = 'AMOUNT_PERCENTAGE_29'; 
      attrib AMOUNT_PERCENTAGE_30 length = 8
         label = 'AMOUNT_PERCENTAGE_30'; 
      attrib AMOUNT_PERCENTAGE_31 length = 8
         label = 'AMOUNT_PERCENTAGE_31'; 
      attrib AMOUNT_PERCENTAGE_32 length = 8
         label = 'AMOUNT_PERCENTAGE_32'; 
      attrib AMOUNT_PERCENTAGE_33 length = 8
         label = 'AMOUNT_PERCENTAGE_33'; 
      attrib AMOUNT_PERCENTAGE_34 length = 8
         label = 'AMOUNT_PERCENTAGE_34'; 
      attrib AMOUNT_PERCENTAGE_35 length = 8
         label = 'AMOUNT_PERCENTAGE_35'; 
      attrib AMOUNT_PERCENTAGE_36 length = 8
         label = 'AMOUNT_PERCENTAGE_36'; 
      attrib AMOUNT_PERCENTAGE_37 length = 8
         label = 'AMOUNT_PERCENTAGE_37'; 
      attrib AMOUNT_PERCENTAGE_38 length = 8
         label = 'AMOUNT_PERCENTAGE_38'; 
      attrib AMOUNT_PERCENTAGE_39 length = 8
         label = 'AMOUNT_PERCENTAGE_39'; 
      attrib AMOUNT_PERCENTAGE_40 length = 8
         label = 'AMOUNT_PERCENTAGE_40'; 
      attrib AMOUNT_PERCENTAGE_41 length = 8
         label = 'AMOUNT_PERCENTAGE_41'; 
      attrib AMOUNT_PERCENTAGE_42 length = 8
         label = 'AMOUNT_PERCENTAGE_42'; 
      attrib AMOUNT_PERCENTAGE_43 length = 8
         label = 'AMOUNT_PERCENTAGE_43'; 
      attrib AMOUNT_PERCENTAGE_44 length = 8
         label = 'AMOUNT_PERCENTAGE_44'; 
      attrib AMOUNT_PERCENTAGE_45 length = 8
         label = 'AMOUNT_PERCENTAGE_45'; 
      attrib AMOUNT_PERCENTAGE_46 length = 8
         label = 'AMOUNT_PERCENTAGE_46'; 
      attrib AMOUNT_PERCENTAGE_47 length = 8
         label = 'AMOUNT_PERCENTAGE_47'; 
      attrib AMOUNT_PERCENTAGE_48 length = 8
         label = 'AMOUNT_PERCENTAGE_48'; 
      attrib AMOUNT_PERCENTAGE_49 length = 8
         label = 'AMOUNT_PERCENTAGE_49'; 
      call missing(of _all_);
      stop;
   run;
   
   %rcSet(&syserr); 
   
   %let etls_tableExist = 0;
   
%mend etls_prepareTarget;
%etls_prepareTarget;

proc sql;
   connect to ORACLE
   ( 
       DBMAX_TEXT=32767 PATH="&ORA_RESASDWH_PATH" user="&ORA_RESASDWH_USER" pw="&ORA_RESASDWH_PWD"
   ); 
   execute 
   ( 
      insert into &ORA_RESASDWH_SCHEMA..MVBS_CASO_REPORT2_REL
      select
         MVBS_CASO_REPORT2_ABS.DISCUNDISC,
         MVBS_CASO_REPORT2_ABS.LEGAL_ENTITY_CODE,
         MVBS_CASO_REPORT2_ABS.GROSSRETRO,
         MVBS_CASO_REPORT2_ABS.AMT_TYPE,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1, MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_TOTAL,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_1  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_1,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_2  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_2,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_3  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
          null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_3,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_4  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_4,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_5  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_5,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_6  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_6,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_7  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_7,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_8  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_8,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_9  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_9,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_10  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_10,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_11  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_11,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_12  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_12,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_13  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_13,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_14  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_14,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_15  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_15,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_16  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_16,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_17  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_17,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_18  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_18,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_19  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_19,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_20  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_20,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_21  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_21,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_22  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_22,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_23  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_23,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_24  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_24,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_25  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_25,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_26  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_26,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_27  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_27,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_28  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_28,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_29  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_29,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_30  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_30,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_31  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_31,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_32  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_32,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_33  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL ,
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_33,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_34  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_34,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_35  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_35,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_36  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_36,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_37  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_37,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_38  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_38,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_39  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_39,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_40  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_40,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_41  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_41,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_42  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_42,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_43  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_43,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_44  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_44,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_45  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_45,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_46  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_46,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_47  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_47,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_48  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_48,
         (MVBS_CASO_REPORT2_ABS.AMOUNT_49  / decode(MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL , 
         null, 1, 0, 1,MVBS_CASO_REPORT2_ABS.AMOUNT_TOTAL )) * 100 as AMOUNT_PERCENTAGE_49
      from
         &ORA_RESASDWH_SCHEMA..MVBS_CASO_REPORT2_ABS MVBS_CASO_REPORT2_ABS
      
   ) by ORACLE; 
   
   %rcSet(&sqlrc); 
   
   disconnect from ORACLE; 
quit;

%global etls_sql_pushDown;
%let etls_sql_pushDown = &sys_sql_ip_all;

%rcSet(&sqlrc); 



/**  Step end SQL Join **/

%let etls_endTime = %sysfunc(datetime(),datetime.);

/* Check return code for job  */ 
%macro etls_jobRCChk; 
   %if (&job_rc ge 5) %then
   %do; 
      %macro etls_sendEmail(address=, message=); 
      
         filename sendMail email "&address" subject='ETL Process Status'; 
      
         %local etls_syntaxcheck; 
         %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
         /* Turn off syntaxcheck option to perform following steps  */ 
         options nosyntaxcheck;
      
         data _null_; 
            file sendMail; 
            dttm = put(datetime(),nldatm.); 
            put dttm "&message."; 
         run; 
      
         /* Reset syntaxcheck option to previous setting  */ 
         options &etls_syntaxcheck; 
      %mend etls_sendEmail; 
      %etls_sendEmail 
         (address = &mail_to, 
          Message = %str(&etls_jobName Error auf &run_system : Error%%superq%(syserrortext%))); 
   %end; 
%mend etls_jobRCChk; 
%etls_jobRCChk; 

/* Check return code for job  */ 
%macro etls_jobRCChk; 
   %if (&job_rc ge 5) %then
   %do; 
      %macro etls_sendFile(directory=, filename=, message=); 
      
         filename sendfile "&directory.&filename"; 
      
         %local etls_syntaxcheck; 
         %let etls_syntaxcheck = %sysfunc(getoption(syntaxcheck)); 
         /* Turn off syntaxcheck option to perform following steps  */ 
         options nosyntaxcheck;
      
         data _null_; 
            file sendFile; 
            dttm = put(datetime(),nldatm.); 
            put dttm "&message."; 
         run; 
      
         /* Reset syntaxcheck option to previous setting  */ 
         options &etls_syntaxcheck; 
      %mend etls_sendFile; 
      %etls_sendFile 
         (FileName = &proj_env/run_control/mvbs_error_&etls_jobName, 
          Message = Error); 
   %end; 
%mend etls_jobRCChk; 
%etls_jobRCChk; 

